"""Небольшие правки

Revision ID: 635b8437d455
Revises: 0d52d44abf8f
Create Date: 2020-05-03 18:21:56.475418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '635b8437d455'
down_revision = '0d52d44abf8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('dialog_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'messages', 'dialogs_info', ['dialog_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'dialog_id')
    # ### end Alembic commands ###
